## 2023 Bakeoff Effect Analysis

In looking across all seasons for a lift in technicals from GBBO being posted to r/baking and r/bakeoff subreddits, there was a clear lift on r/bakeoff while r/baking remained flat.

In doing this analysis, I encountered two confounds that appeared to impact the data:
1. In earlier seasons, the GBBO aired significantly later in the U.S. than in the U.K.
2. During the height of the COVID-19 pandemic (03/2020 - 06/2021), hobbyist baking took off and posts to r/baking skyrocketed, potentially drowning out any signal.

In 2023, we were past the height of the pandemic and uptick in hobbyist bakers, and GBBO episodes started airing on Netflix 3 days after their U.K air date. This notebook is a look at whether Season 14 (2023) technical baking trends look any different on r/baking or r/bakeoff.

In [1]:
import pandas as pd
import numpy as np

In [2]:
baking_reddit = pd.read_csv('/Users/rachelvice/Development/Lede/Projects/bakeoff_effect/data/GBBO_reddit_posts_merged.csv')
bakeoff_reddit = pd.read_csv('/Users/rachelvice/Development/Lede/Projects/bakeoff_effect/data/GBBO_bakeoff_reddit_posts_merged.csv')

In [8]:
technicals = pd.read_csv('/Users/rachelvice/Development/Lede/Projects/bakeoff_effect/data/TechnicalBakes.csv')
technicals

,Airdate,Season,Episode,Theme,Signature,Signature Time (min),Technical,Technical Time (min),Showstopper,Showstopper Time (min),challenge level numeric
0,8/17/2010,1,1,cake,cake,180.0,victoria sandwich,NaN,chocolate celebration cake,NaN,1.0
1,8/24/2010,1,2,biscuit,personality biscuits,120.0,scones,60.0,"meringue, choux, and macaron petits fours",240.0,1.0
2,8/31/2010,1,3,bread,signature bread,210.0,cob,150.0,12 sweet and 12 savoury rolls,360.0,NaN
3,9/7/2010,1,4,pudding,classic pudding,150.0,mini hot lemon soufflés,40.0,"crumble, bread, & suet puddings",300.0,NaN
4,9/14/2010,1,5,pastry,savoury pie,150.0,cornish pasties,90.0,savory canapés and sweet tartlets,300.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
129,10/31/2023,14,6,botanical,12 individual spiced buns,165.0,lemon and thyme drizzle cake,90.0,floral dessert,240.0,NaN
130,11/7/2023,14,7,desserts,8 creme caramels,165.0,orange and ginger treacle puddings,90.0,meringue bombe,NaN,2.0
131,11/14/2023,14,8,party,12 sausage rolls,150.0,caterpiller cake,150.0,anything but beige buffet,270.0,2.0
132,11/21/2023,14,9,patisserie,24 financiers,120.0,tart aux pommes,150.0,millefoglie,240.0,2.0
133,11/28/2023,14,10,final,8 éclairs,135.0,lardy cake slices,180.0,tiered celebration cake,270.0,2.0

In [9]:
season_2023 = technicals[technicals['Season'] == 14]
season_2023

,Airdate,Season,Episode,Theme,Signature,Signature Time (min),Technical,Technical Time (min),Showstopper,Showstopper Time (min),challenge level numeric
124,9/26/2023,14,1,cake,vertical layer cake,NaN,the signature chocolate cake with fresh raspbe...,120.0,3d shaped animal cake,240.0,2.0
125,10/3/2023,14,2,biscuits,12 marshmallow biscuits,NaN,custard creams,90.0,illusion biscuit meal,240.0,1.0
126,10/10/2023,14,3,bread,cottage loaf,120.0,devonshire splits,NaN,plaited centrepiece loaf,NaN,2.0
127,10/18/2023,14,4,chocolate,chocolate torte,NaN,white chocolate and blackberry cheesecakes,NaN,edible chocolate box cake,NaN,2.0
128,10/24/2023,14,5,pastry,savoury picnic pie,NaN,dauphinoise pithivier,165.0,decorative sweet pie display,NaN,NaN
129,10/31/2023,14,6,botanical,12 individual spiced buns,165.0,lemon and thyme drizzle cake,90.0,floral dessert,240.0,NaN
130,11/7/2023,14,7,desserts,8 creme caramels,165.0,orange and ginger treacle puddings,90.0,meringue bombe,NaN,2.0
131,11/14/2023,14,8,party,12 sausage rolls,150.0,caterpiller cake,150.0,anything but beige buffet,270.0,2.0
132,11/21/2023,14,9,patisserie,24 financiers,120.0,tart aux pommes,150.0,millefoglie,240.0,2.0
133,11/28/2023,14,10,final,8 éclairs,135.0,lardy cake slices,180.0,tiered celebration cake,270.0,2.0

In [10]:
technicals = season_2023['Technical']

In [11]:
#load r/baking and r/bakeoff lift files

baking_lift = pd.read_csv('/Users/rachelvice/Development/Lede/Projects/bakeoff_effect/data/baking_lift.csv')
bakeoff_lift = pd.read_csv('/Users/rachelvice/Development/Lede/Projects/bakeoff_effect/data/bakeoff_lift.csv')

In [14]:
r_baking_lift_2023 = baking_lift[baking_lift['Technical'].isin(technicals)]
r_bakeoff_lift_2023 = bakeoff_lift[baking_lift['Technical'].isin(technicals)]

print(r_baking_lift_2023[['Technical', 'lift_diff']])

                                            Technical  lift_diff
7                                      custard creams   0.000000
8                                   devonshire splits   0.000275
25         white chocolate and blackberry cheesecakes   0.000000
29                                   caterpiller cake   0.000000
44                       lemon and thyme drizzle cake   0.000000
61                                    tart aux pommes  -0.000210
63  the signature chocolate cake with fresh raspbe...   0.000000

/var/folders/5j/38n921dd2nsfk3nmjffgnd2w0000gn/T/ipykernel_30336/4051540608.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  r_bakeoff_lift_2023 = bakeoff_lift[baking_lift['Technical'].isin(technicals)]

In [16]:
r_baking_lift_2023

,Technical,baseline_share,post_air_share,zero_baseline_flag,lift,lift_diff
7,custard creams,0.00000,0.000000,True,NaN,0.000000
8,devonshire splits,0.00000,0.000275,True,NaN,0.000275
25,white chocolate and blackberry cheesecakes,0.00000,0.000000,True,NaN,0.000000
29,caterpiller cake,0.00000,0.000000,True,NaN,0.000000
44,lemon and thyme drizzle cake,0.00000,0.000000,True,NaN,0.000000
61,tart aux pommes,0.00021,0.000000,False,0.0,-0.000210
63,the signature chocolate cake with fresh raspbe...,0.00000,0.000000,True,NaN,0.000000

In [17]:
r_bakeoff_lift_2023

            Technical  baseline_share  post_air_share  lift_diff
7          dampfnudel             0.0        0.015873   0.015873
8  lemon meringue pie             0.0        0.000000   0.000000

In [21]:
r_bakeoff_lift_2023

            Technical  baseline_share  post_air_share  lift_diff
7          dampfnudel             0.0        0.015873   0.015873
8  lemon meringue pie             0.0        0.000000   0.000000

### Conclusion

Season 14 (2023) is too small of a sample to test on its own, but the available data is consistent with the data found across the full dataset. There is little to no reaction on r/baking, and at least some technicals being attempted on r/bakeoff.